<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<?php echo $this->getRequest()->getParams('pid')?>
<body>
    <div class="header"><?php echo $this->getChild('header')->toHtml();?></div>
    <div class="content">content
   
        <div class="left">Left</div>
        <div class="middle">Middle</div>
        <div class="right">Right</div>
    </div>
    <div class="footer"><?php echo $this->getChild('footer')->toHtml();?></div>
    
</body>
</html>