<?php
// Mage::getSingleton('core/session')->remove('customerId');
  $productModel = $this->getProduct();
?>

		  <h1>Product Form</h1><br><br>
         <form action="<?php echo $this->getUrl("admin/catalog_product/save")?>" method="post" class="product">
		
		 <label for="pid" hidden>Product Id:</label>
	<input type="hidden" id="pid" name="pdata[product_id]" value="<?php echo $productModel->getProductId()?>" required ><br><br>
	<label for="sku">SKU:</label>
	<input type="text" id="sku" name="pdata[sku]" placeholder="enter stock keeping unit" value="<?php echo $productModel->getSku()?>" required ><br><br>
	<label for="name">Name:</label>
	<input type="text" id="name" name="pdata[name]" placeholder="enter product name" value="<?php echo $productModel->getName()?>" required ><br><br>
	<label for="color">Color:</label>
	<input type="color" id="color" name="pdata[color]"  value="<?php echo $productModel->getColor()?>" required ><br><br>
	<label for="size">Size:</label>
	<input type="text" id="size" name="pdata[size]" placeholder="enter size" value="<?php echo $productModel->getSize()?>" required ><br><br>
	<label for="description">Description:</label><br>
        <textarea id="description" name="pdata[description]" rows="4" cols="50">
        </textarea><br>
	<label for="imagelink">Image Link:</label>
	<input type="file" id="imagelink" name="pdata[image_link]" placeholder="enter image link" value="<?php echo $productModel->getImageLink()?>" ><br><br>
	<label for="link">Link:</label>
	<input type="file" id="link" name="pdata[link]" placeholder="enter link" value="<?php echo $productModel->getLink()?>" ><br><br>
	<label for="cid">Category Id:</label>
	<input type="text" id="cid" name="pdata[category_id]" placeholder="enter category id" value="<?php echo $productModel->getCategoryId()?>" required ><br><br>
	<label for="price">Price:</label>
	<input type="text" id="price" name="pdata[price]" placeholder="enter price" value="<?php echo $productModel->getPrice()?>" required ><br><br>
    <label for="mfrcost">Manufacturer Cost:</label>
	<input type="text" id="mercost" name="pdata[mfr_cost]" placeholder="enter manufacturer cost" value="<?php echo $productModel->getMfrCost()?>" required ><br><br>
    <label for="shipcost">Shipping Cost:</label>
	<input type="text" id="shipcost" name="pdata[shipping_cost]" placeholder="enter shipping cost" value="<?php echo $productModel->getShippingCost()?>" required ><br><br>
    <label for="totalcost">Total Cost:</label>
	<input type="text" id="totalcost" name="pdata[total_cost]" placeholder="enter total cost" value="<?php echo $productModel->getTotalCost()?>" required ><br><br>
    <label for="mper">Margin Percentage:</label>
	<input type="text" id="mper" name="pdata[margin_percentage]" placeholder="enter margin percentage" value="<?php echo $productModel->getMarginPercentage()?>" required ><br><br>
	<label for="mprice">Min Price:</label>
	<input type="text" id="mprice" name="pdata[min_price]" placeholder="enter min price" value="<?php echo $productModel->getMinPrice()?>" required ><br><br>
	<label for="status">Status:</label>
		<select id="status" name="pdata[status]" >
			<option value="select">--Select--</option>
			<option value=1 <?php echo $productModel->getStatus() == 'Enable' ? 'selected':""?> >Enabled</option>
			<option value=0 <?php echo $productModel->getStatus() == 'Disable' ? 'selected':""?>>Disabled</option>
		</select><br/><br/>	
	<input type="submit" name="submit" value="submit"/>
</form>
	
		













