list phtml content
<pre>
<?php
$productCollection = Mage::getModel('catalog/product')->getCollection()
   // ->addFieldToFilter('product_name','bet')
    // ->addFieldToFilter('product_name',['like' => 'bet'])
    // ->addFieldToFilter('product_name',['gt' => 'bet'])
    // ->addFieldToFilter('product_name',['in' => 'bet'])
    // ->addFieldToFilter('product_name',['between' => 'bet'])
    ;
    //print_r($productCollection->getData());
?>

<table>

<!-- <?php ///$productModel = Mage::getModel('catalog/product')->load(2); ?> -->
<div class="table" style="margin-top:20px;">
    <table border="1px solid black">
        <tr>
        <th>Product id</th>
            <th>SKU</th>
            <th>Name</th>
            <th>Color</th>
            <th>Size</th>
            <th>Description</th>
            <th>Image Link</th>
            <th>Link</th>
            <th>Price</th>
            <th>Mfr Cost</th>
            <th>Shipping Cost</th>
            <th>Total cost</th>
            <th>Margin Percentage</th>
            <th>Min Price</th>
            <th>Status</th>
            <th>Update</th>
            <th>Delete</th>
        </tr>
            <?php foreach($productCollection->getData() as $product) {
            // var_dump($product->getStatus());
            //print_r($productModel);
            //echo get_class($productCollection); 
            ?>
        <tr>
        <tr>
            <td><?php print_r($product->getProductId());?></td>
            <td><?php print_r($product->getSku());?></td>
            <td><?php print_r($product->getName());?></td>
            <td><?php print_r($product->getColor());?></td>
            <td><?php print_r($product->getSize());?></td>
            <td><?php print_r($product->getDescription());?></td>
            <td><?php print_r($product->getImageLink());?></td>
            <td><?php print_r($product->getLink());?></td>
            <td><?php print_r($product->getPrice());?></td>
            <td><?php print_r($product->getMfrCost());?></td>
            <td><?php print_r($product->getShippingCost());?></td>
            <td><?php print_r($product->getTotalCost());?></td>
            <td><?php print_r($product->getMarginPercentage());?></td>
            <td><?php print_r($product->getMinPrice());?></td>
            <td><?php print_r($product->getStatus());?></td>
            <td><button class="edit-button"><a href='<?php echo $this->getUrl('admin/catalog_product/form')?>?id=<?php echo $product->getId()?>'>Edit</a></button></td>
            <td><button class="delete-button"><a href='<?php echo $this->getUrl('admin/catalog_product/delete')?>?id=<?php echo $product->getId()?>'>Delete</a></button></td>
        </tr>
            <?php } ?>
    </table>
</div>

</table>





