
<!-- //<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous"> -->
<!-- <h1>head.phtml</h1> -->
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <?php $js=$this->getJs();?>
    <?php if(count($js)): ?>
        <?php foreach($js as $_js): ?>
            <script type ="" src= "<?php echo $_js;?>" > </script>  
            <?php  echo $_js."<br>";  ?>
        <?php endforeach; ?> 
    <?php endif;?>


    <?php $css=$this->getCss();?>
    <?php if(count($css)): ?>
        <?php foreach($css as $_css): ?>
            <link rel ="" href= "<?php echo $_css;?>" >  
            <?php
            echo $_css."<br>";
            ?>
        <?php endforeach; ?> 
    <?php endif;?>
    


    
    


