

<h1>head.phtml</h1>

    <?php $js=$this->getJs();?>
    <?php if(count($js)): ?>
        <?php foreach($js as $_js): ?>
            <script type ="" src= "<?php echo $_js;?>" > </script>  
            <?php  echo $_js."<br>";  ?>
        <?php endforeach; ?> 
    <?php endif;?>


    <?php $css=$this->getCss();?>
    <?php if(count($css)): ?>
        <?php foreach($css as $_css): ?>
            <link rel ="" href= "<?php echo $_css;?>" > </script>  
            <?php
            echo $_css."<br>";
            ?>
        <?php endforeach; ?> 
    <?php endif;?>
    


    
    


