list phtml content
<pre>
<?php
$customerCollection = Mage::getModel('customer/customer')->getCollection();
   // ->addFieldToFilter('product_name','bet')
    // ->addFieldToFilter('product_name',['like' => 'bet'])
    // ->addFieldToFilter('product_name',['gt' => 'bet'])
    // ->addFieldToFilter('product_name',['in' => 'bet'])
    // ->addFieldToFilter('product_name',['between' => 'bet'])

    //print_r($customerCollection->getData());
    
?>

<div class="table" style="margin-top:20px;">
    <table border="1px solid black">
        <tr>
            <th>Customer Id</th>
            <th>Customer Email</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Billing Address</th>
            <th>Billing City</th>
            <th>Billing Region</th>
            <th>Billing Country</th>
            <th>Billing Phone</th>
            <th>Shipping Address</th>
            <th>Shipping City</th>
            <th>Shipping region</th>
            <th>Shipping Country</th>
            <th>Shipping Phone</th>
            <th>Default</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
        <?php foreach($customerCollection->getData() as $data): ?>
            
                    <tr>
                        <td><?php echo $data->getCustomerId();?></td>
                        <td><?php echo $data->getCustomerEmail();?></td>
                        <td><?php echo $data->getFirstName();?></td>
                        <td><?php echo $data->getLastName();?></td>
                        <td><?php echo $data->getBillingAddress();?></td>
                        <td><?php echo $data->getBillingAddress();?></td>
                        <td><?php echo $data->getBillingCity();?></td>
                        <td><?php echo $data->getBillingRegion();?></td>
                        <td><?php echo $data->getBillingCountry();?></td>
                        <td><?php echo $data->getBillingPhone();?></td>
                        <td><?php echo $data->getShippingAddress();?></td>
                        <td><?php echo $data->getShippingCity();?></td>
                        <td><?php echo $data->getShippingRegion();?></td>
                        <td><?php echo $data->getShippingCountry();?></td>
                        <td><?php echo $data->getShippingPhone();?></td>
                        <td><?php echo $data->getDefault();?></td>
                        <td>
                            <a href="register?id=<?php echo $data->getCustomerId(); ?>"><button class ="edit">Edit</button></a>
                        </td>
                        <td>
                            <a href="delete?id=<?php echo $data->getCustomerId(); ?>"><button class ="delete"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
          <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0z"/>
          <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4zM2.5 3h11V2h-11z"/>
          </svg> Delete</button></a>
                        </td>
                        </tr>
                        <?php endforeach; ?>
    </table>
</div>







