
<form action="<?php echo $this->getUrl("customer/account/save")?>" method="post" class="product">
    <input type="hidden" id="customer_id" name="customer[customer_id]"  required><br><br>

    <label for="customer_email">Customer Email:</label><br>
    <input type="email" id="customer_email" name="customer[customer_email]" required><br><br>

    <label for="first_name">First Name:</label><br>
    <input type="text" id="first_name" name="customer[first_name]" required><br><br>

    <label for="last_name">Last Name:</label><br>
    <input type="text" id="last_name" name="customer[last_name]" required><br><br>

    <label for="billing_address">Billing Address:</label><br>
    <input type="text" id="billing_address" name="customer[billing_address]" required><br><br>

    <label for="billing_city">Billing City:</label><br>
    <input type="text" id="billing_city" name="customer[billing_city]" required><br><br>

    <label for="billing_region">Billing Region:</label><br>
    <input type="text" id="billing_region" name="customer[billing_region]"><br><br>

    <label for="billing_country">Billing Country:</label><br>
    <input type="text" id="billing_country" name="customer[billing_country]" required><br><br>

    <label for="billing_phone">Billing Phone:</label><br>
    <input type="tel" id="billing_phone" name="customer[billing_phone]" required><br><br>

    <label for="shipping_address">Shipping Address:</label><br>
    <input type="text" id="shipping_address" name="customer[shipping_address]" required><br><br>

    <label for="shipping_city">Shipping City:</label><br>
    <input type="text" id="shipping_city" name="customer[shipping_city]" required><br><br>

    <label for="shipping_region">Shipping Region:</label><br>
    <input type="text" id="shipping_region" name="customer[shipping_region]"><br><br>

    <label for="shipping_country">Shipping Country:</label><br>
    <input type="text" id="shipping_country" name="customer[shipping_country]" required><br><br>

    <label for="shipping_phone">Shipping Phone:</label><br>
    <input type="tel" id="shipping_phone" name="customer[shipping_phone]" required><br><br>

    <label for="default">Default:</label><br>
    <input type="checkbox" id="default" name="customer[default]"><br><br>

    <input type="submit" name="submit" value="Submit">
</form>
