<?php if(Mage::getModel('sales/quote')->load(Mage::getSingleton('core/session')->get('quote_id'))->getGrandTotal()!=0)
{
print_r(Mage::getSingleton('core/session')->get('quote_id'));
?>

<?php
    $salesQuote = Mage::getModel('sales/quote')->getCollection()
                    ->addFieldToFilter('quote_id',Mage::getSingleton('core/session')->get('quote_id'));
    $salesQuoteItem = Mage::getModel('sales/quote_item')->getCollection()
                    ->addFieldToFilter('quote_id',Mage::getSingleton('core/session')->get('quote_id'));
    // $salesQuoteItem = Mage::getModel('sales/quote')->getItemCollection();
    // print_r($salesQuoteItem);
?>
<?php
$quoteId= Mage::getSingleton("core/session")->get('quote_id');

?>
<main>
    <div class="cart-container">
        <?php foreach ($salesQuoteItem->getData() as $items): ?>
            <?php $productCollection = Mage::getModel('catalog/product')->getCollection()
                ->addFieldToFilter('product_id', $items->getProductId());
                ?>
            <?php foreach ($productCollection->getData() as $productModel): ?>
                <div class="cart-item">
                    <div class="cart-item-image">
                        <img src="<?php echo Mage::getBaseUrl() . '/media/product/' . $productModel->getImageLink(); ?>" alt="Product Image">
                    </div>
                    <div class="cart-item-details">
                        <h3><?php echo $productModel->getName(); ?></h3>
                        <!-- <p><strong>SKU:</strong> <?php // echo $productModel->getSku(); ?></p> -->
                        <p>Size:<?php echo $productModel->getSize() ?></p>
                        <p>Color:<?php echo $productModel->getColor() ?></p>
                        <p><strong>Price:</strong> Rs.<?php echo $productModel->getPrice(); ?></p>
                        <form method="POST" action="<?php //echo  $this->getUrl('/sales/quote/add') ?>">
                            <label for="qty">Quantity:</label>
                            <input type="number" name="add[qty]" id="qty" min="1" max="50" required value="<?php echo $items->getQty() ?>"><br>
                            <p><strong>Total Price:</strong> Rs.<?php echo $items->getRowTotal();?></p>
                            <button class="remove-item" type="button"><a href="<?php echo Mage::getBaseUrl()."sales/quote/delete?id=".$items->getId();?>">Remove Item</a></button>
                        </form>
                    </div>
                </div>
            <?php endforeach; ?>
        <?php endforeach; ?>
        <?php foreach($salesQuote->getData() as $items): ?>
            <div class="cart-total">
                <p><strong>Sub Total:</strong><?php echo "Rs.".$items->getGrandTotal() - ($items->getGrandTotal())/(1+100/$items->getTaxPercent())?></p>
                <p><strong>(Tax :<?php echo $items->getTaxPercent(); ?>%) :</strong><?php echo "Rs.".($items->getGrandTotal())/(1+100/$items->getTaxPercent()) ?></p>
                <p><strong>Cart Total:</strong> Rs.<?php echo $items->getGrandTotal(); ?></p>
            </div>
        <?php endforeach; ?>
        <button class="checkout" type="button"><a href="<?php echo Mage::getBaseUrl()."sales/quote/checkout"?>">Checkout</a></button>
    </div>
</main>
<?php }else{ ?>
<h2>your cart is empty</h2>
<?php }?>